### PR TITLE
Add new option to PartSubtype

### PR DESCRIPTION
**Pull request by linuxgurugamer**
I added a new option: allowSwitchFromInFlight (defaults to true).  This is intended to allow a tank to be able to have different types in the editor, but once in flight, to not allow a tank which contains a toxic material (or something incompatible with other tyupes) to be switched in flight

I need this for my life support mod, IFI, have a new tank which can contains two different types of O2 (switchable in flight) and two other toxic materials, which I don't want switchable in flight

My alternative would be to duplicate the parts, I'm trying to minimize the part count.

### CODE REVIEW

**Comment by blowfishpro** [comment]
Okay so just to clarify the idea would be that if this subtype is selected, you can't switch off of it once in the flight scene?

**Comment by blowfishpro** [comment]
Also any chance you could change the merge into a rebase?  I'd like to keep the commit history clean.  If not I can probably figure out how.

**Comment by linuxgurugamer** [comment]
I've never done that, would be nervous to try on someone else's mod 
I'd suggest reading this, might be helpful, I don't have a lot of time right now to test this:

https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by linuxgurugamer** [comment]
> Okay so just to clarify the idea would be that if this subtype is selected, you can't switch off of it once in the flight scene?

yes

**Comment by blowfishpro** [comment]
I wanted to keep the merge commit on master which unfortunately that option doesn't allow.  I merged manually but this is done.

**Pull request closed without merging**
